export const GET_ALL_CAMPGROUNDS = 'GET_ALL_CAMPGROUNDS';
export const GET_ALL_CAMPGROUNDS_SUCCESS = 'GET_ALL_CAMPGROUNDS_SUCCESS';
export const GET_ALL_CAMPGROUNDS_FAILURE = 'GET_ALL_CAMPGROUNDS_FAILURE';
export const ADD_CAMPGROUND = 'ADD_CAMPGROUND';
export const GET_CAMPGROUND_DETAILS = 'GET_CAMPGROUND_DETAILS';
export const UPDATE_CAMPGROUND = 'UPDATE_CAMPGROUND';
export const DELETE_CAMPGROUND = 'DELETE_CAMPGROUND';
